CREATE TABLE proposals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text,
  upvotes integer default 0 not null,
  downvotes integer default 0 not null
);

CREATE TABLE comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  proposal_id bigint references proposals(id) on delete cascade not null,
  user_name text,
  text text
);

CREATE TABLE votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  proposal_id bigint references proposals(id) on delete cascade not null,
  user_id uuid,
  vote_type text check (vote_type in ('up', 'down'))
);

CREATE TABLE big_issue_votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  choice text check (choice in ('agree', 'disagree')),
  user_id uuid
);
